import type { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'bw.co.tirelo.app',
  appName: 'Tirelo Services',
  webDir: 'www',
  plugins: {
    PushNotifications: {
      // Show heads-up + badge + sound when a push arrives in foreground.
      presentationOptions: ['badge', 'sound', 'alert'],
    },
  },
  // Deep links: tirelo:// custom scheme + Universal/App Links domain.
  // (Android intent filters / iOS associated domains are configured in the
  //  native projects generated by `npx cap add android|ios`.)
};

export default config;
