'use strict';
// Secure Software Supply Chain (Phase 10, Part 8). SLSA-shaped build integrity: provenance
// attestation, signed builds and artifacts, container/image signing, dependency verification,
// reproducible builds, package integrity, release verification and binary provenance.
//
// 🔒 Signing here uses the platform's SYNTHETIC signing identity, clearly labelled. Production
// signing keys are human-built and HSM-custodied (Sigstore/cosign or an internal CA are the
// documented drop-ins); this module governs the ATTESTATION STRUCTURE and its verification,
// which is the part that has to be right regardless of who holds the key.
//
// Deterministic: an attestation over the same inputs produces the same digest, which is exactly
// what makes a reproducible build checkable.
const fs = require('node:fs');
const path = require('node:path');
const { hash, signing } = require('../twin');

const ROOT = path.join(__dirname, '..', '..');

// SLSA build levels and what each actually requires.
const SLSA_LEVELS = {
  1: { name: 'Provenance exists', requires: ['Build process is scripted', 'Provenance is generated and available'] },
  2: { name: 'Signed provenance, hosted build', requires: ['Provenance is signed', 'Build runs on a hosted service', 'Source is version controlled'] },
  3: { name: 'Hardened build platform', requires: ['Build service is hardened', 'Provenance is non-forgeable', 'Build is isolated'] },
  4: { name: 'Hermetic, reproducible', requires: ['Build is hermetic', 'Build is reproducible', 'Two-person review of all changes'] },
};

// What this platform currently claims, and honestly why.
const CLAIMED_LEVEL = 2;
const LEVEL_EVIDENCE = {
  1: { met: true, evidence: 'The build is fully scripted (npm scripts + Dockerfile) and provenance is generated by this module on every release.' },
  2: { met: true, evidence: 'Provenance is signed (🔒 synthetic identity in the reference build), source is version controlled, and the container build is reproducible from the repo root.' },
  3: { met: false, evidence: 'Requires a hardened, isolated hosted build service with non-forgeable provenance — an infrastructure commitment, not a code change. Tracked in the migration roadmap.' },
  4: { met: false, evidence: 'Requires hermetic builds and enforced two-person review. Reproducibility is already demonstrable (zero third-party dependencies); hermeticity and review enforcement are organisational.' },
};

class SupplyChainAttestation {
  constructor({ clock = () => Date.now() } = {}) { this._clock = clock; this._attestations = new Map(); this._artifacts = new Map(); this._seq = 0; }

  // --- Provenance ------------------------------------------------------------------------

  // Build provenance in in-toto/SLSA shape. The subject is the artifact digest; the predicate
  // records who built what, from which source, with which dependencies.
  buildProvenance({ artifact, artifactDigest, builder = 'njtip-reference-builder', sourceRef, sourceDigest, dependencies = [], buildType = 'https://njtip/build/npm-container@v1', reproducible = true }) {
    if (!artifact || !artifactDigest) throw new Error('provenance requires an artifact and its digest');
    if (!sourceRef || !sourceDigest) { const e = new Error('provenance requires the source it was built from'); e.failClosed = true; throw e; }
    const predicate = {
      buildType, builder: { id: builder },
      invocation: { configSource: { uri: sourceRef, digest: { sha256: sourceDigest } } },
      materials: dependencies.map((d) => ({ uri: d.name, digest: { sha256: d.digest } })),
      metadata: { reproducible, completeness: { parameters: true, environment: true, materials: true } },
    };
    const statement = {
      _type: 'https://in-toto.io/Statement/v1',
      subject: [{ name: artifact, digest: { sha256: artifactDigest } }],
      predicateType: 'https://slsa.dev/provenance/v1',
      predicate,
    };
    const digest = hash.sha256(statement);                    // deterministic over the statement
    const attestation = {
      id: 'ATT-' + (++this._seq).toString().padStart(4, '0'),
      statement, digest, signature: signing.sign(digest),
      signedBy: 'njtip-synthetic-signing-identity 🔒',
      slsaLevel: CLAIMED_LEVEL, createdAt: this._clock(),
    };
    this._attestations.set(attestation.id, attestation);
    this._artifacts.set(artifactDigest, attestation.id);
    return { ...attestation };
  }

  attestation(id) { const a = this._attestations.get(id); return a ? JSON.parse(JSON.stringify(a)) : null; }
  attestations() { return [...this._attestations.values()].map((a) => JSON.parse(JSON.stringify(a))); }

  // Verify an attestation: the statement must hash to the recorded digest AND the signature
  // must verify. Tampering with any field breaks the first check — that is the point.
  verify(id) {
    const a = this._attestations.get(id);
    if (!a) return { valid: false, reason: 'unknown attestation' };
    const recomputed = hash.sha256(a.statement);
    if (recomputed !== a.digest) return { valid: false, reason: 'statement does not match its digest — the attestation was altered' };
    if (!signing.verify(a.digest, a.signature)) return { valid: false, reason: 'signature does not verify' };
    return { valid: true, artifact: a.statement.subject[0].name, digest: a.digest, slsaLevel: a.slsaLevel, note: '🔒 Synthetic signing identity in the reference build; production uses HSM-custodied keys.' };
  }
  // Verify by artifact digest — the check a deploy step actually performs.
  verifyArtifact(artifactDigest) {
    const id = this._artifacts.get(artifactDigest);
    if (!id) return { valid: false, reason: 'no provenance attestation for this artifact — an unattested artifact is not deployable' };
    return { ...this.verify(id), attestation: id };
  }

  // --- SBOM attestation, dependency verification, reproducibility ---------------------------

  // An SBOM attestation binds the bill of materials to the artifact it describes.
  sbomAttestation({ artifact, artifactDigest, sbom }) {
    if (!sbom) throw new Error('an SBOM is required');
    const statement = {
      _type: 'https://in-toto.io/Statement/v1',
      subject: [{ name: artifact, digest: { sha256: artifactDigest } }],
      predicateType: 'https://cyclonedx.org/bom',
      predicate: { components: sbom.dependencies.length + sbom.devDependencies.length, runtime: sbom.runtime, builtinsUsed: sbom.builtinsUsed, thirdParty: sbom.dependencies },
    };
    const digest = hash.sha256(statement);
    return { statement, digest, signature: signing.sign(digest), thirdPartyCount: sbom.dependencies.length + sbom.devDependencies.length };
  }

  // Dependency verification: every declared dependency must be pinned to a digest and come
  // from an approved supplier. With zero third-party dependencies this is trivially satisfied —
  // and the check still runs, because that is how it stays true.
  verifyDependencies({ dependencies = [], approvedSuppliers = [] } = {}) {
    const findings = [];
    for (const d of dependencies) {
      if (!d.digest) findings.push({ dependency: d.name, issue: 'not pinned to a digest' });
      if (approvedSuppliers.length && !approvedSuppliers.includes(d.supplier)) findings.push({ dependency: d.name, issue: `supplier '${d.supplier}' is not approved` });
    }
    return { dependencies: dependencies.length, findings, verified: findings.length === 0, note: 'A dependency without a pinned digest is an unverifiable dependency.' };
  }

  // Reproducible build check: build the same inputs twice and compare digests.
  verifyReproducible({ buildFn }) {
    if (typeof buildFn !== 'function') throw new Error('a build function is required');
    const first = hash.sha256(buildFn());
    const second = hash.sha256(buildFn());
    return { reproducible: first === second, first, second, note: 'Two builds over identical inputs must produce an identical digest.' };
  }

  // --- Release verification ------------------------------------------------------------------

  // The gate a release must pass. FAIL-CLOSED: any missing attestation blocks the release.
  verifyRelease({ artifact, artifactDigest, sbom, dependencies = [], approvedSuppliers = [], signedContainer = false }) {
    const checks = [];
    const prov = this.verifyArtifact(artifactDigest);
    checks.push({ check: 'build-provenance', pass: prov.valid, detail: prov.reason || `attested at SLSA L${prov.slsaLevel}` });
    const deps = this.verifyDependencies({ dependencies, approvedSuppliers });
    checks.push({ check: 'dependency-verification', pass: deps.verified, detail: deps.findings.length ? deps.findings.map((f) => `${f.dependency}: ${f.issue}`).join('; ') : `${deps.dependencies} dependencies verified` });
    const sbomOk = !!(sbom && typeof sbom.runtime === 'string');
    checks.push({ check: 'sbom-attestation', pass: sbomOk, detail: sbomOk ? `runtime: ${sbom.runtime}` : 'no SBOM supplied' });
    checks.push({ check: 'artifact-signature', pass: prov.valid, detail: prov.valid ? 'signature verifies' : 'unsigned or unverifiable' });
    checks.push({ check: 'container-signature', pass: !!signedContainer, detail: signedContainer ? 'image signature present' : 'container image is not signed' });
    const failed = checks.filter((c) => !c.pass);
    return {
      artifact, artifactDigest, checks, failed: failed.map((c) => c.check),
      verified: failed.length === 0,
      failClosed: true, authorizes: false,
      note: failed.length ? 'Release BLOCKED: supply-chain verification failed.' : 'Supply chain verified. This does not authorize deployment — go-live is a recorded human decision.',
    };
  }

  // --- SLSA posture -------------------------------------------------------------------------------

  slsaPosture() {
    return {
      claimedLevel: CLAIMED_LEVEL,
      levels: Object.entries(SLSA_LEVELS).map(([level, l]) => ({ level: Number(level), ...l, ...LEVEL_EVIDENCE[level] })),
      honestGaps: Object.entries(LEVEL_EVIDENCE).filter(([, e]) => !e.met).map(([level, e]) => ({ level: Number(level), why: e.evidence })),
      note: 'The claimed level is the level the evidence supports. Levels 3 and 4 need infrastructure and organisational commitments, and are recorded as gaps rather than claimed.',
    };
  }

  // Full supply-chain report for the CI dashboard.
  report({ sbom = null, dependencies = [], buildFn = null } = {}) {
    return {
      slsa: this.slsaPosture(),
      attestations: this.attestations().map((a) => ({ id: a.id, artifact: a.statement.subject[0].name, digest: a.digest, verified: this.verify(a.id).valid })),
      dependencies: this.verifyDependencies({ dependencies }),
      sbom: sbom ? this.sbomAttestation({ artifact: 'njtip-app', artifactDigest: hash.sha256(sbom), sbom }) : null,
      reproducible: buildFn ? this.verifyReproducible({ buildFn }) : null,
      note: '🔒 Synthetic signing identity in the reference build. Production drop-ins: Sigstore/cosign or an internal CA with HSM-custodied keys.',
    };
  }
}

// Build the source digest for the repo's own tracked sources (deterministic, order-stable).
function sourceDigest() {
  const SRC = path.join(ROOT, 'src');
  const files = [];
  const walk = (dir) => { for (const n of fs.readdirSync(dir).sort()) { const f = path.join(dir, n); if (fs.statSync(f).isDirectory()) walk(f); else if (f.endsWith('.js')) files.push(f); } };
  walk(SRC);
  return hash.sha256(files.map((f) => ({ file: path.relative(ROOT, f).split(path.sep).join('/'), digest: hash.sha256(fs.readFileSync(f, 'utf8')) })));
}

module.exports = { SupplyChainAttestation, SLSA_LEVELS, CLAIMED_LEVEL, LEVEL_EVIDENCE, sourceDigest };
